spring:
  application:
    name: auth-service

server:
  port: 6000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.11:8761/eureka