apiVersion: v1
kind: Service
metadata:
  name: gorae-auth-service
spec:
  selector:
    app: gorae-auth
  ports:
    - protocol: 'TCP'
      port: 6000
      targetPort: 6000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorae-auth
  labels:
    app: gorae-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorae-auth
  template:
    metadata:
      labels:
        app: gorae-auth
    spec:
      containers:
        - name: gorae-auth
          image: lifetwoshot/gorae-auth:latest
          imagePullPolicy: Always
